version: "3"
services:
    api:
        build: .
        container_name: api
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        environment:
            - PORT=3000
            - MONGO_URL=mongodb://mongo:27017/noderest

    mongo:
        image: mongo:latest
        container_name: mongo
        volumes:
            - /var/lib/docker/volumes/apimongo/_data/db:/data/db 
        ports:
            - "27017:27017"
        command: mongod --smallfiles --oplogSize 128 --replSet rs0 

