version: "3"
services:
   api:
       build: .
       container_name: api
       restart: always
       ports:
        - "3000:3000"
       links:
        - mongo
       depends_on:
        - mongo

   mongo:
      image: mongo:latest
      container_name: mongodb
      volumes:
         - /var/lib/docker/volumes/mongo/_data/db:/data/db 
      ports:
         - "27017:27017"
      command: mongod --smallfiles --oplogSize 128 --replSet rs0 

